# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: navigation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'navigation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10navigation.proto\x12\x05robot\"8\n\x06Header\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\t\x12\x0b\n\x03sec\x18\x02 \x01(\x05\x12\x0f\n\x07nanosec\x18\x03 \x01(\x05\"(\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"8\n\nQuaternion\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01w\x18\x04 \x01(\x01\"N\n\x04Pose\x12\x1e\n\x08position\x18\x01 \x01(\x0b\x32\x0c.robot.Point\x12&\n\x0borientation\x18\x02 \x01(\x0b\x32\x11.robot.Quaternion\"G\n\x0bPoseStamped\x12\x1d\n\x06header\x18\x01 \x01(\x0b\x32\r.robot.Header\x12\x19\n\x04pose\x18\x02 \x01(\x0b\x32\x0b.robot.Pose\"\x07\n\x05\x45mpty2v\n\x0cRobotService\x12\x30\n\nStreamGoal\x12\x0c.robot.Empty\x1a\x12.robot.PoseStamped0\x01\x12\x34\n\x10SendLocalization\x12\x12.robot.PoseStamped\x1a\x0c.robot.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'navigation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEADER']._serialized_start=27
  _globals['_HEADER']._serialized_end=83
  _globals['_POINT']._serialized_start=85
  _globals['_POINT']._serialized_end=125
  _globals['_QUATERNION']._serialized_start=127
  _globals['_QUATERNION']._serialized_end=183
  _globals['_POSE']._serialized_start=185
  _globals['_POSE']._serialized_end=263
  _globals['_POSESTAMPED']._serialized_start=265
  _globals['_POSESTAMPED']._serialized_end=336
  _globals['_EMPTY']._serialized_start=338
  _globals['_EMPTY']._serialized_end=345
  _globals['_ROBOTSERVICE']._serialized_start=347
  _globals['_ROBOTSERVICE']._serialized_end=465
# @@protoc_insertion_point(module_scope)
