# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    from . import navigation_pb2 as navigation__pb2
except ImportError:
    import navigation_pb2 as navigation__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in navigation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamGoal = channel.unary_stream(
                '/robot.RobotService/StreamGoal',
                request_serializer=navigation__pb2.Empty.SerializeToString,
                response_deserializer=navigation__pb2.PoseStamped.FromString,
                _registered_method=True)
        self.SendLocalization = channel.unary_unary(
                '/robot.RobotService/SendLocalization',
                request_serializer=navigation__pb2.PoseStamped.SerializeToString,
                response_deserializer=navigation__pb2.Empty.FromString,
                _registered_method=True)


class RobotServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamGoal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendLocalization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamGoal': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamGoal,
                    request_deserializer=navigation__pb2.Empty.FromString,
                    response_serializer=navigation__pb2.PoseStamped.SerializeToString,
            ),
            'SendLocalization': grpc.unary_unary_rpc_method_handler(
                    servicer.SendLocalization,
                    request_deserializer=navigation__pb2.PoseStamped.FromString,
                    response_serializer=navigation__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robot.RobotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robot.RobotService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamGoal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/robot.RobotService/StreamGoal',
            navigation__pb2.Empty.SerializeToString,
            navigation__pb2.PoseStamped.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendLocalization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.RobotService/SendLocalization',
            navigation__pb2.PoseStamped.SerializeToString,
            navigation__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
